language: c
# safelist
branches:
  only:
  - master
script:
- LINKAGE=static CFLAGS="-O2 -Wall -coverage" ./configure && make && sudo make install && sudo ldconfig && make test
#- ./configure && make && sudo make install && sudo ldconfig && make test
arch:
- amd64
#- arm64
after_success:
  - bash <(curl -s https://codecov.io/bash)
