
#line 3 "lex.cligen_parse.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cligen_parse_create_buffer
#define yy_delete_buffer cligen_parse_delete_buffer
#define yy_flex_debug cligen_parse_flex_debug
#define yy_init_buffer cligen_parse_init_buffer
#define yy_flush_buffer cligen_parse_flush_buffer
#define yy_load_buffer_state cligen_parse_load_buffer_state
#define yy_switch_to_buffer cligen_parse_switch_to_buffer
#define yyin cligen_parsein
#define yyleng cligen_parseleng
#define yylex cligen_parselex
#define yylineno cligen_parselineno
#define yyout cligen_parseout
#define yyrestart cligen_parserestart
#define yytext cligen_parsetext
#define yywrap cligen_parsewrap
#define yyalloc cligen_parsealloc
#define yyrealloc cligen_parserealloc
#define yyfree cligen_parsefree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cligen_parserestart(cligen_parsein  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int cligen_parseleng;

extern FILE *cligen_parsein, *cligen_parseout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cligen_parsetext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cligen_parsetext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cligen_parserestart()), so that the user can continue scanning by
	 * just pointing cligen_parsein at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cligen_parsetext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int cligen_parseleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cligen_parsewrap()'s to do buffer switches
 * instead of setting up a fresh cligen_parsein.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cligen_parserestart (FILE *input_file  );
void cligen_parse_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cligen_parse_create_buffer (FILE *file,int size  );
void cligen_parse_delete_buffer (YY_BUFFER_STATE b  );
void cligen_parse_flush_buffer (YY_BUFFER_STATE b  );
void cligen_parsepush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cligen_parsepop_buffer_state (void );

static void cligen_parseensure_buffer_stack (void );
static void cligen_parse_load_buffer_state (void );
static void cligen_parse_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cligen_parse_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cligen_parse_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cligen_parse_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cligen_parse_scan_bytes (yyconst char *bytes,int len  );

void *cligen_parsealloc (yy_size_t  );
void *cligen_parserealloc (void *,yy_size_t  );
void cligen_parsefree (void *  );

#define yy_new_buffer cligen_parse_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cligen_parseensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cligen_parse_create_buffer(cligen_parsein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cligen_parseensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cligen_parse_create_buffer(cligen_parsein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *cligen_parsein = (FILE *) 0, *cligen_parseout = (FILE *) 0;

typedef int yy_state_type;

extern int cligen_parselineno;

int cligen_parselineno = 1;

extern char *cligen_parsetext;
#define yytext_ptr cligen_parsetext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cligen_parsetext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cligen_parseleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[170] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   76,   17,
        1,    4,    3,    8,    9,    2,    6,    7,    5,   16,
       12,   18,   13,   14,   10,   15,   66,   56,   59,   65,
       58,   62,   63,   57,   61,   60,   66,   64,   67,   22,
       19,   22,   21,   74,   73,   27,   26,   24,   25,   23,
       27,   47,   28,   29,   37,   33,   34,   47,   46,   31,
       30,   35,   47,   36,   47,   47,   47,   47,   47,   47,
       32,   55,   48,   49,   75,   55,   54,   52,   51,   55,
       50,   72,   71,   68,   70,   69,   17,    0,   11,   66,

       66,   56,   66,   66,   20,   27,   27,   26,   27,   27,
       47,   47,   28,   46,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   55,   55,   48,   54,   55,   55,
       55,   45,   47,   47,   47,   47,   47,   47,   47,   53,
       47,   47,   47,   47,   47,   47,   38,   47,   47,   47,
       47,   39,   47,   42,   47,   47,   40,   44,   47,   43,
       47,   47,   47,   47,   47,   47,   47,   41,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        7,    1,    8,    9,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,    1,   18,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       19,   20,   21,    1,    1,    1,   22,    1,   23,   24,

       25,   26,   27,   28,   29,    1,   30,   31,    1,   32,
       33,   34,    1,   35,   36,   37,    1,    1,   38,   39,
       40,    1,   41,   42,   43,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    2,    3,    4,    5,    6,    6,    1,    5,    1,
        1,    1,    7,    5,    8,    5,    7,    8,    9,    1,
        9,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    9,    5
    } ;

static yyconst flex_int16_t yy_base[187] =
    {   0,
        0,   42,   84,  126,    7,    9,  319,  318,   20,   33,
      169,    0,  211,  252,  317,  316,   35,   61,  318,  297,
      734,  734,  734,  312,  734,  734,  734,  734,  734,  734,
      734,  293,  734,  734,  734,  734,  295,  311,  734,  734,
      734,  734,  734,  734,  734,  734,  335,  734,  734,  734,
      734,  303,  734,  734,  734,  286,  303,  284,  734,  734,
       92,  283,  299,  734,  734,  734,  734,    5,   55,  734,
      734,  734,  377,  734,    4,   34,    6,   48,   52,   50,
      734,  277,  294,  734,  734,   59,   90,  734,  734,  418,
      734,  734,  734,  734,  734,  734,  273,    0,  734,  272,

      459,  288,  269,    0,  734,  268,   94,  285,  266,  121,
      265,  501,  280,  106,   96,  261,    0,   86,    8,  116,
       60,   83,   32,  117,  260,  542,  277,  132,  101,  258,
        0,  127,  125,  128,  196,  133,  135,  138,  200,  137,
      141,   62,  202,  205,  216,  206,  232,  219,  139,  213,
      209,  146,  223,  145,  207,  226,  102,  100,  229,   56,
      256,  227,  248,  243,  254,  247,  255,   14,  734,  584,
      593,  602,  611,  620,  629,  638,  647,  656,  663,  672,
      681,  690,  699,  707,  716,  724
    } ;

static yyconst flex_int16_t yy_def[187] =
    {   0,
      170,  170,  171,  171,  172,  172,  173,  173,  174,  174,
      169,   11,  175,  175,  176,  176,  177,  177,  169,  178,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  178,  169,  169,  169,  169,  179,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  180,  169,  169,  169,
      169,  169,  169,  169,  169,  181,  169,  181,  169,  169,
      182,  183,  169,  169,  169,  169,  169,  183,  183,  169,
      169,  169,  184,  169,  183,  183,  183,  183,  183,  183,
      169,  185,  169,  169,  169,  185,  185,  169,  169,  186,
      169,  169,  169,  169,  169,  169,  178,   32,  169,  179,

      180,  169,  179,  101,  169,  181,  182,  169,  181,  182,
      183,  184,  169,  183,  183,  183,  112,  183,  183,  183,
      183,  183,  183,  183,  185,  186,  169,  185,  185,  185,
      126,  183,  183,  183,  183,  183,  183,  183,  183,  185,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,    0,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169
    } ;

static yyconst flex_int16_t yy_nxt[778] =
    {   0,
      169,   21,   22,  169,   23,   24,   25,  169,   26,   51,
       52,   51,   52,   27,   28,   29,  114,   30,   31,   32,
       33,   57,   58,  112,  112,  112,   53,  112,   53,  134,
      120,  118,   59,  112,   57,   58,   60,   94,   95,   61,
       34,   35,   36,   21,   22,   59,   23,   24,   25,   60,
       26,  112,   61,  112,   96,   27,   28,   29,  138,   30,
       31,   32,   33,   94,   95,  115,  114,  112,  119,  112,
      128,  112,  121,  122,  112,  112,  123,  124,  126,  112,
       96,  112,   34,   35,   36,   38,   39,   40,   41,   42,
       43,  136,   44,  106,  106,  106,  106,   45,  149,   46,

      129,  128,  112,   47,  106,  112,  106,  132,  106,  126,
      106,  110,  140,  110,  137,  112,  115,  114,  133,  112,
      126,  112,  106,  106,   48,  112,   49,   38,   39,   40,
       41,   42,   43,  106,   44,  112,  112,  106,  132,   45,
      110,   46,  129,  128,  112,   47,  112,  112,  140,  139,
      142,  126,  112,  141,  112,  135,  126,  112,  112,  144,
      112,  145,  146,  148,  112,  112,   48,  155,   49,   62,
       63,   64,   65,   62,   66,   67,   68,   62,   68,   62,
       69,   70,   62,   62,   62,   71,   62,   72,   73,   74,
       62,   75,   62,   62,   76,   62,   62,   62,   77,   78,

       62,   62,   62,   79,   80,   62,   62,   62,   62,   62,
       81,   62,   83,   84,   85,  112,   85,   85,   86,  112,
       86,  112,   87,   88,  112,  112,  112,   89,  112,   85,
       90,   85,  112,  143,  150,  112,  157,  147,  112,  159,
      152,  151,  112,  154,  153,  112,  112,  156,  112,  160,
      163,  112,   91,   83,   84,   85,  158,   85,   85,   86,
      161,   86,  112,   87,   88,  162,  112,  112,   89,  165,
       85,   90,   85,  112,  112,  112,  164,  126,  127,  126,
      112,  113,  166,  167,  112,  107,  108,  107,  101,  102,
      168,  101,   98,   91,   97,  127,  126,   97,   97,   97,

      113,   97,  112,  107,  108,  107,   97,   97,   97,  105,
       97,   97,  102,   97,  101,   99,   98,  169,   85,   85,
       55,   55,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,   97,   97,   97,  100,  169,  100,  100,
      100,  100,  169,  100,  169,  169,  169,  169,  100,  169,
      100,  169,  169,  169,  104,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  100,  169,  100,  111,  169,
      111,  169,  111,  111,  169,  169,  169,  169,  169,  111,
      169,  169,  169,  111,  169,  111,  117,  111,  169,  169,

      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  111,  125,
      169,  125,  169,  125,  125,  169,  169,  169,  169,  169,
      125,  169,  169,  169,  125,  169,  125,  131,  125,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  125,
      100,  169,  100,  100,  100,  100,  169,  100,  169,  169,
      169,  169,  100,  169,  100,  169,  169,  169,  104,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  100,

      169,  100,  111,  169,  111,  169,  111,  111,  169,  169,
      169,  169,  169,  111,  169,  169,  169,  111,  169,  111,
      117,  111,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  111,  125,  169,  125,  169,  125,  125,  169,
      169,  169,  169,  169,  125,  169,  169,  169,  125,  169,
      125,  131,  125,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  125,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   37,   37,   37,   37,   37,   37,   37,

       37,   37,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   97,  169,  169,   97,
      169,  169,   97,  100,  169,  169,  169,  169,  169,  100,
      100,  100,  103,  103,  169,  103,  103,  103,  103,  103,
      103,  106,  169,  106,  106,  106,  106,  169,  106,  106,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  111,

      169,  169,  169,  111,  169,  169,  111,  116,  116,  169,
      116,  116,  116,  116,  116,  116,  125,  169,  169,  169,
      125,  169,  169,  125,  130,  130,  169,  130,  130,  130,
      130,  130,  130,   19,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169
    } ;

static yyconst flex_int16_t yy_chk[778] =
    {   0,
        0,    1,    1,    0,    1,    1,    1,    0,    1,    5,
        5,    6,    6,    1,    1,    1,   68,    1,    1,    1,
        1,    9,    9,   75,   68,   77,    5,  119,    6,  119,
       77,   75,    9,  168,   10,   10,    9,   17,   17,    9,
        1,    1,    1,    2,    2,   10,    2,    2,    2,   10,
        2,  123,   10,   76,   17,    2,    2,    2,  123,    2,
        2,    2,    2,   18,   18,   69,   69,   78,   76,   80,
       86,   79,   78,   79,   69,  160,   79,   80,   86,  121,
       18,  142,    2,    2,    2,    3,    3,    3,    3,    3,
        3,  121,    3,   61,   61,  107,  107,    3,  142,    3,

       87,   87,  122,    3,   61,  118,  107,  115,   61,   87,
      107,   61,  129,  107,  122,  115,  114,  114,  118,  158,
      129,  157,  110,  110,    3,  114,    3,    4,    4,    4,
        4,    4,    4,  110,    4,  120,  124,  110,  132,    4,
      110,    4,  128,  128,  133,    4,  132,  134,  140,  124,
      134,  128,  136,  133,  137,  120,  140,  138,  149,  136,
      141,  137,  138,  141,  154,  152,    4,  149,    4,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   13,   13,   13,  135,   13,   13,   13,  139,
       13,  143,   13,   13,  144,  146,  155,   13,  151,   13,
       13,   13,  150,  135,  143,  145,  151,  139,  148,  155,
      145,  144,  153,  148,  146,  156,  162,  150,  159,  156,
      162,  147,   13,   14,   14,   14,  153,   14,   14,   14,
      159,   14,  164,   14,   14,  161,  166,  163,   14,  164,
       14,   14,   14,  165,  167,  161,  163,  130,  127,  125,
      116,  113,  165,  166,  111,  109,  108,  106,  103,  102,
      167,  100,   97,   14,   32,   83,   82,   32,   32,   32,

       63,   32,   62,   58,   57,   56,   32,   32,   32,   52,
       32,   32,   38,   32,   37,   24,   20,   19,   16,   15,
        8,    7,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   32,   32,   32,   47,    0,   47,   47,
       47,   47,    0,   47,    0,    0,    0,    0,   47,    0,
       47,    0,    0,    0,   47,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   47,    0,   47,   73,    0,
       73,    0,   73,   73,    0,    0,    0,    0,    0,   73,
        0,    0,    0,   73,    0,   73,   73,   73,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   73,   90,
        0,   90,    0,   90,   90,    0,    0,    0,    0,    0,
       90,    0,    0,    0,   90,    0,   90,   90,   90,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   90,
      101,    0,  101,  101,  101,  101,    0,  101,    0,    0,
        0,    0,  101,    0,  101,    0,    0,    0,  101,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  101,

        0,  101,  112,    0,  112,    0,  112,  112,    0,    0,
        0,    0,    0,  112,    0,    0,    0,  112,    0,  112,
      112,  112,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  112,  126,    0,  126,    0,  126,  126,    0,
        0,    0,    0,    0,  126,    0,    0,    0,  126,    0,
      126,  126,  126,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  126,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  171,  171,  171,  171,  171,  171,  171,

      171,  171,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  178,    0,    0,  178,
        0,    0,  178,  179,    0,    0,    0,    0,    0,  179,
      179,  179,  180,  180,    0,  180,  180,  180,  180,  180,
      180,  181,    0,  181,  181,  181,  181,    0,  181,  181,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  183,

        0,    0,    0,  183,    0,    0,  183,  184,  184,    0,
      184,  184,  184,  184,  184,  184,  185,    0,    0,    0,
      185,    0,    0,  185,  186,  186,    0,  186,  186,  186,
      186,  186,  186,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cligen_parse_flex_debug;
int cligen_parse_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cligen_parsetext;
#line 1 "cligen_parse.l"
/*
  ***** BEGIN LICENSE BLOCK *****
 
  Copyright (C) 2001-2017 Olof Hagsand

  This file is part of CLIgen.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  Alternatively, the contents of this file may be used under the terms of
  the GNU General Public License Version 2 or later (the "GPL"),
  in which case the provisions of the GPL are applicable instead
  of those above. If you wish to allow use of your version of this file only
  under the terms of the GPL, and not to allow others to
  use your version of this file under the terms of Apache License version 2, indicate
  your decision by deleting the provisions above and replace them with the 
  notice and other provisions required by the GPL. If you do not delete
  the provisions above, a recipient may use your version of this file under
  the terms of any one of the Apache License version 2 or the GPL.

  ***** END LICENSE BLOCK *****

*/
#line 36 "cligen_parse.l"


#include "cligen_config.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <netinet/in.h>

#include "cligen_parse.tab.h" /* generated */

#include "cligen_buf.h"
#include "cligen_var.h"
#include "cligen_cvec.h"
#include "cligen_gen.h"
#include "cligen_parse.h"

/* Redefine main lex function so that you can send arguments to it */
#define YY_DECL int cligen_parselex(void *_ya)

/* typecast macro */
#define _YA ((struct cligen_parse_yacc_arg *)_ya)

#define     MAXBUF  4*4*64*1024

#define MAX(x,y) ((x)>(y)?(x):(y))
#define MIN(x,y) ((x)<(y)?(x):(y))

#undef cligen_parsewrap
int 
cligen_parsewrap(void)
{
  return 1;
}

/* like strdup but strip \:s */
static char *
stripdup(char *s0)
{
  char *s1;
  char *s;

  if ((s1 = strdup(s0)) == NULL){
    fprintf(stderr, "%s: strdup: %s\n", __FUNCTION__, strerror(errno));
    return NULL;
  }
  while ((s = index(s1, '\\')) != NULL)
    memmove(s, s+1, strlen(s)); 
  return s1;
}

/*
  See block_chart for lex states.
*/









#line 802 "lex.cligen_parse.c"

#define INITIAL 0
#define OPTION 1
#define HELP 2
#define COMMENT 3
#define NAMEORTYPE 4
#define VARIABLE 5
#define CHOICE 6
#define ESCAPE 7
#define STRING 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cligen_parselex_destroy (void );

int cligen_parseget_debug (void );

void cligen_parseset_debug (int debug_flag  );

YY_EXTRA_TYPE cligen_parseget_extra (void );

void cligen_parseset_extra (YY_EXTRA_TYPE user_defined  );

FILE *cligen_parseget_in (void );

void cligen_parseset_in  (FILE * in_str  );

FILE *cligen_parseget_out (void );

void cligen_parseset_out  (FILE * out_str  );

int cligen_parseget_leng (void );

char *cligen_parseget_text (void );

int cligen_parseget_lineno (void );

void cligen_parseset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cligen_parsewrap (void );
#else
extern int cligen_parsewrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cligen_parsetext, cligen_parseleng, 1, cligen_parseout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cligen_parsein )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cligen_parsein ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cligen_parsein))==0 && ferror(cligen_parsein)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cligen_parsein); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cligen_parselex (void);

#define YY_DECL int cligen_parselex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cligen_parsetext and cligen_parseleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 103 "cligen_parse.l"

#line 999 "lex.cligen_parse.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cligen_parsein )
			cligen_parsein = stdin;

		if ( ! cligen_parseout )
			cligen_parseout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cligen_parseensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cligen_parse_create_buffer(cligen_parsein,YY_BUF_SIZE );
		}

		cligen_parse_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cligen_parsetext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 170 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 734 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 104 "cligen_parse.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "cligen_parse.l"
{ BEGIN(OPTION); return *cligen_parsetext; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "cligen_parse.l"
{ _YA->ya_lex_state =INITIAL; BEGIN(COMMENT); }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 107 "cligen_parse.l"
{ _YA->ya_linenum++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "cligen_parse.l"
{ BEGIN(OPTION); return *cligen_parsetext; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 109 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 110 "cligen_parse.l"
{ return MY_EOF; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 111 "cligen_parse.l"
{ BEGIN(NAMEORTYPE); return *cligen_parsetext; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 112 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 113 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 114 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "cligen_parse.l"
{ BEGIN(HELP); return PDQ; /* parenth double-q*/  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 116 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 117 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 118 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 119 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 120 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 121 "cligen_parse.l"
{ 
                            cligen_parselval.string = stripdup(cligen_parsetext);
                            return NAME; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 124 "cligen_parse.l"
{ return -1; }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 126 "cligen_parse.l"
{ _YA->ya_linenum++; 
                            cligen_parselval.string = strdup(cligen_parsetext);
                            return CHAR; }
	YY_BREAK
case YY_STATE_EOF(HELP):
#line 129 "cligen_parse.l"
{ return MY_EOF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 130 "cligen_parse.l"
{ BEGIN(INITIAL); return DQP; /* double-quote parenthes */}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 131 "cligen_parse.l"
{ _YA->ya_lex_state = HELP; BEGIN(ESCAPE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 132 "cligen_parse.l"
{ cligen_parselval.string = strdup(cligen_parsetext);
                            return CHAR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 135 "cligen_parse.l"
{ BEGIN(INITIAL); return *cligen_parsetext; }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 136 "cligen_parse.l"
{ _YA->ya_linenum++; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 137 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 138 "cligen_parse.l"
{ BEGIN(VARIABLE); return ' '; }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 139 "cligen_parse.l"
{ 
                            cligen_parselval.string = strdup(cligen_parsetext);
                            return NAME; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 143 "cligen_parse.l"
{ return ' '; }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 144 "cligen_parse.l"
{ _YA->ya_linenum++; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 145 "cligen_parse.l"
{ BEGIN(INITIAL); return *cligen_parsetext; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 146 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 147 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 148 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 149 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 150 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 151 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 152 "cligen_parse.l"
{ _YA->ya_lex_string_state =VARIABLE;BEGIN(STRING); return DQ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 153 "cligen_parse.l"
{ return V_SHOW; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 154 "cligen_parse.l"
{ return V_RANGE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 155 "cligen_parse.l"
{ return V_LENGTH; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 156 "cligen_parse.l"
{ return V_FRACTION_DIGITS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 157 "cligen_parse.l"
{ BEGIN(CHOICE);return V_CHOICE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 158 "cligen_parse.l"
{ return V_KEYWORD; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 159 "cligen_parse.l"
{ return V_REGEXP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 160 "cligen_parse.l"
{ cligen_parselval.string = strdup(cligen_parsetext); return DECIMAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 161 "cligen_parse.l"
{ cligen_parselval.string = strdup(cligen_parsetext); return NUMBER;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 162 "cligen_parse.l"
{ 
                                 cligen_parselval.string = strdup(cligen_parsetext);
                                 return NAME; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 166 "cligen_parse.l"
{ return ' '; }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 167 "cligen_parse.l"
{ _YA->ya_linenum++; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 168 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 169 "cligen_parse.l"
{ BEGIN(INITIAL); return *cligen_parsetext; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 170 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 171 "cligen_parse.l"
{ cligen_parselval.string = strdup(cligen_parsetext); return DECIMAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 172 "cligen_parse.l"
{ cligen_parselval.string = strdup(cligen_parsetext); return NUMBER;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 173 "cligen_parse.l"
{ 
                                 cligen_parselval.string = strdup(cligen_parsetext);
                                 return NAME; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 177 "cligen_parse.l"

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 178 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 179 "cligen_parse.l"
{ _YA->ya_lex_state =INITIAL; BEGIN(COMMENT); }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 180 "cligen_parse.l"
{ _YA->ya_linenum++; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 181 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 182 "cligen_parse.l"
{ BEGIN(INITIAL); return *cligen_parsetext;}
	YY_BREAK
case YY_STATE_EOF(OPTION):
#line 183 "cligen_parse.l"
{ return MY_EOF; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 184 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 185 "cligen_parse.l"
{ return *cligen_parsetext; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 186 "cligen_parse.l"
{ BEGIN(INITIAL); return *cligen_parsetext;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 187 "cligen_parse.l"
{ _YA->ya_lex_string_state =INITIAL;BEGIN(STRING); return DQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 188 "cligen_parse.l"
{ 
                                 cligen_parselval.string = strdup(cligen_parsetext);
                                 return NAME; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 191 "cligen_parse.l"
{ return -1;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 193 "cligen_parse.l"
{ _YA->ya_linenum++; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 194 "cligen_parse.l"
{ _YA->ya_lex_state = STRING; BEGIN(ESCAPE); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 195 "cligen_parse.l"
{ BEGIN(_YA->ya_lex_string_state); return DQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 196 "cligen_parse.l"
{ cligen_parselval.string = strdup(cligen_parsetext);
                            return CHAR;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 199 "cligen_parse.l"
{ BEGIN(_YA->ya_lex_state); 
                             cligen_parselval.string = strdup(cligen_parsetext); 
                             return CHAR; }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 203 "cligen_parse.l"
{ _YA->ya_linenum++; BEGIN(_YA->ya_lex_state);}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 204 "cligen_parse.l"
{ return MY_EOF; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 205 "cligen_parse.l"

	YY_BREAK
case 75:
YY_RULE_SETUP
#line 208 "cligen_parse.l"
ECHO;
	YY_BREAK
#line 1498 "lex.cligen_parse.c"
case YY_STATE_EOF(NAMEORTYPE):
case YY_STATE_EOF(VARIABLE):
case YY_STATE_EOF(CHOICE):
case YY_STATE_EOF(ESCAPE):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cligen_parsein at a new source and called
			 * cligen_parselex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cligen_parsein;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cligen_parsewrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cligen_parsetext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cligen_parselex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cligen_parserealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cligen_parserestart(cligen_parsein  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cligen_parserealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 170 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 170 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 169);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cligen_parsetext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cligen_parserestart(cligen_parsein );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cligen_parsewrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cligen_parsetext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cligen_parserestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cligen_parseensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cligen_parse_create_buffer(cligen_parsein,YY_BUF_SIZE );
	}

	cligen_parse_init_buffer(YY_CURRENT_BUFFER,input_file );
	cligen_parse_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cligen_parse_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cligen_parsepop_buffer_state();
	 *		cligen_parsepush_buffer_state(new_buffer);
     */
	cligen_parseensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cligen_parse_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cligen_parsewrap()) processing, but the only time this flag
	 * is looked at is after cligen_parsewrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cligen_parse_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cligen_parsein = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cligen_parse_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cligen_parsealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cligen_parse_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cligen_parsealloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cligen_parse_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cligen_parse_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cligen_parse_create_buffer()
 * 
 */
    void cligen_parse_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cligen_parsefree((void *) b->yy_ch_buf  );

	cligen_parsefree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cligen_parserestart() or at EOF.
 */
    static void cligen_parse_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cligen_parse_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cligen_parse_init_buffer was _probably_
     * called from cligen_parserestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cligen_parse_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cligen_parse_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cligen_parsepush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cligen_parseensure_buffer_stack();

	/* This block is copied from cligen_parse_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cligen_parse_switch_to_buffer. */
	cligen_parse_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cligen_parsepop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cligen_parse_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cligen_parse_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cligen_parseensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cligen_parsealloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cligen_parseensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cligen_parserealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cligen_parseensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cligen_parse_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cligen_parsealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cligen_parse_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cligen_parse_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cligen_parselex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cligen_parse_scan_bytes() instead.
 */
YY_BUFFER_STATE cligen_parse_scan_string (yyconst char * yystr )
{
    
	return cligen_parse_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cligen_parselex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cligen_parse_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cligen_parsealloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cligen_parse_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cligen_parse_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cligen_parse_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cligen_parsetext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cligen_parsetext[cligen_parseleng] = (yy_hold_char); \
		(yy_c_buf_p) = cligen_parsetext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cligen_parseleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cligen_parseget_lineno  (void)
{
        
    return cligen_parselineno;
}

/** Get the input stream.
 * 
 */
FILE *cligen_parseget_in  (void)
{
        return cligen_parsein;
}

/** Get the output stream.
 * 
 */
FILE *cligen_parseget_out  (void)
{
        return cligen_parseout;
}

/** Get the length of the current token.
 * 
 */
int cligen_parseget_leng  (void)
{
        return cligen_parseleng;
}

/** Get the current token.
 * 
 */

char *cligen_parseget_text  (void)
{
        return cligen_parsetext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cligen_parseset_lineno (int  line_number )
{
    
    cligen_parselineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cligen_parse_switch_to_buffer
 */
void cligen_parseset_in (FILE *  in_str )
{
        cligen_parsein = in_str ;
}

void cligen_parseset_out (FILE *  out_str )
{
        cligen_parseout = out_str ;
}

int cligen_parseget_debug  (void)
{
        return cligen_parse_flex_debug;
}

void cligen_parseset_debug (int  bdebug )
{
        cligen_parse_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cligen_parselex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cligen_parsein = stdin;
    cligen_parseout = stdout;
#else
    cligen_parsein = (FILE *) 0;
    cligen_parseout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cligen_parselex_init()
     */
    return 0;
}

/* cligen_parselex_destroy is for both reentrant and non-reentrant scanners. */
int cligen_parselex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cligen_parse_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cligen_parsepop_buffer_state();
	}

	/* Destroy the stack itself. */
	cligen_parsefree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cligen_parselex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cligen_parsealloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cligen_parserealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cligen_parsefree (void * ptr )
{
	free( (char *) ptr );	/* see cligen_parserealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 208 "cligen_parse.l"



/*
 * cgl_init
 * Initialize scanner.
 */
int
cgl_init(struct cligen_parse_yacc_arg *ya)
{
  BEGIN(INITIAL);
  ya->ya_lexbuf = cligen_parse_scan_string (ya->ya_parse_string);
#if 1 /* XXX: just to use unput to avoid warning  */
  if (0)
    yyunput(0, ""); 
#endif

  return 0;
}

/*
 * cgl_exit
 * free buffers
 * Even within Flex version 2.5 (this is assumed), freeing buffers is different.
 */
int
cgl_exit(struct cligen_parse_yacc_arg *ya)
{
    cligen_parse_delete_buffer(ya->ya_lexbuf);
#if defined(YY_FLEX_SUBMINOR_VERSION) && YY_FLEX_SUBMINOR_VERSION >= 9
    cligen_parselex_destroy();  /* modern */
#else
    yy_init = 1;      /* This does not quite free all buffers */
#endif
    return 0;
}



